### ISSUE TITLE
WMR platform fails to build

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/WindowsMixedReality#109]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

There seems to be an API update on the WMR platform Spatial Awareness API's that is preventing the UWP platform from building in UWP

```
Reference rewriter: Error: method `System.Numerics.Vector3[] Windows.Perception.Spatial.SpatialStageFrameOfReference::TryGetMovementBounds(Windows.Perception.Spatial.SpatialCoordinateSystem)` doesn't exist in target framework. It is referenced from XRTK.WindowsMixedReality.dll at System.Boolean XRTK.WindowsMixedReality.Providers.BoundarySystem.WindowsMixedRealityBoundaryDataProvider::TryGetBoundaryGeometry(System.Collections.Generic.List`1<UnityEngine.Vector3>&).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1219)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:209)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

It can still run in the editor with spatial awareness turned off but has limited functionality.

## To Reproduce

Create a project, target UWP, Build

**Comment by StephenHodgson** [comment]
It's not failing. It's also a known unity bug fixed in 2020+ that hasn't been backported yet. 

Tested and works even with error

**Comment by StephenHodgson** [comment]
https://forum.unity.com/threads/getting-a-reference-rewriter-error-for-spatialstageframeofreference.909581/#post-6574855

**Comment by SimonDarksideJ** [comment]
Except this is preventing a build completing successfully in 2019.4

**Comment by StephenHodgson** [comment]
I don't believe it actually is. The builds have been passing in CI/CD with this error for quite some time

**Comment by StephenHodgson** [comment]
![image](https://user-images.githubusercontent.com/13334553/101845903-c9c2a880-3b1d-11eb-92be-8f92e278fef6.png)
https://dev.azure.com/xrtk/Mixed%20Reality%20Toolkit/_build/results?buildId=5574&view=results

**Comment by SimonDarksideJ** [comment]
I didn't think we were doing uwp builds on our server, only windows standalone, which won't show up as the classes are bound by uwp directives.

**Comment by StephenHodgson** [comment]
We're doing uwp builds on the server.

**Comment by StephenHodgson** [comment]
https://dev.azure.com/xrtk/Mixed%20Reality%20Toolkit/_build/results?buildId=5574&view=logs&j=0ab14b9f-e499-56d5-97b1-fd98b70ea339&t=3fa529ca-c925-5304-b42f-2bbd21f9750e&l=12

**Comment by StephenHodgson** [comment]
![image](https://user-images.githubusercontent.com/13334553/101846153-5b321a80-3b1e-11eb-9c28-d880537f500f.png)

**Comment by StephenHodgson** [comment]
@SimonDarksideJ you could reply in that Unity forum thread I linked above, but @TautvydasZilys said it was cosmetic, and not really high on the priority list for 2019 LTS. When 2020 goes LTS and we transition this will go away anyway

**Comment by SimonDarksideJ** [comment]
Tested on Preview Core-171 / WMR -27 and builds fine
