### ISSUE TITLE
WMR controllers are no longer recognised or detected in new XR system

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/WindowsMixedReality#111]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

During 0.2.0 testing in a clean UPM project, WMR controllers fail to be recognised in either the editor or a build

## To Reproduce

Create a project using WMR and run, either in editor or UWP

## Expected behavior

Controllers

## Actual behavior

None

## Your Setup

- Operation system: WIndows 10 UWP
- Unity Version 2019.4.16
- XRTK Version 0.2.0 Preview Core 171, WMR 27

**Comment by StephenHodgson** [comment]
None of the controllers have been implemented in the new unity XR system, nor do we plan on utilizing it in the project.

We want to get the native input from the windows apis directly.

**Comment by StephenHodgson** [comment]
See #83 and #94
