### ISSUE TITLE
Duplicate pointers per controller

### ISSUE THREAD

**Issue by FejZa** [XRTK/WindowsMixedReality#29]
## Describe the bug
Each active controller when using a WMR headset gets two pointers in space, where one is rotated around 45 on the x axis. Only one of the pointers is actually working and triggering focus etc.

## To Reproduce
- Create a Unity project
- Import XRTK and WMR extension
- Setup scene for XRTK
- Switch platform to UWP
- Hit play in the editor
- Observe the issue

## Expected behavior
Same behaviour as with e.g. standalone VR. Only one pointer per controller.

## Information(please complete the following information):
- XRTK development branch
- Unity 2019.1.7f1

**Comment by FejZa** [comment]
Closed since it's not only WMR related. Will create an issue in the core repo.

**Comment by StephenHodgson** [comment]
@FejZa btw you can actually transfer issues from one repo to the next.

![image](https://user-images.githubusercontent.com/13334553/59930086-23a64e80-9410-11e9-8d83-a3abccfa66f6.png)
