### ISSUE TITLE
HoloLensWorldManager failed to return a world coordinate system!

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/WindowsMixedReality#50]
## Describe the bug
When running the XRTK in the current insider build for windows, the following error is repeatedly spammed into the console:

```
HoloLensWorldManager failed to return a world coordinate system!
UnityEngine.XR.WSA.SurfaceObserver:SetVolumeAsAxisAlignedBox(Vector3, Vector3)
XRTK.WindowsMixedReality.SpatialObservers.WindowsMixedRealitySpatialMeshObserver:ConfigureObserverVolume(Vector3, Vector3) (at Library/PackageCache/com.xrtk.wmr@0.1.9/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs:131)
XRTK.WindowsMixedReality.SpatialObservers.WindowsMixedRealitySpatialMeshObserver:Update() (at Library/PackageCache/com.xrtk.wmr@0.1.9/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs:68)
XRTK.Services.MixedRealityToolkit:UpdateAllServices() (at Library/PackageCache/com.xrtk.core@0.1.29/Services/MixedRealityToolkit.cs:1262)
XRTK.Services.MixedRealityToolkit:Update() (at Library/PackageCache/com.xrtk.core@0.1.29/Services/MixedRealityToolkit.cs:683)
```

## To Reproduce
Target the UWP platform, run.

## Information(please complete the following information):
 - Version: 2019.1.14
- Release package

**Comment by FejZa** [comment]
Can confirm, I am not running an insider build though. Latest public windows version.

**Comment by FejZa** [comment]
@SimonDarksideJ just to clarify. You are talking about in-editor run here as well? Because I noticed it in editor but on device I didn't.

**Comment by SimonDarksideJ** [comment]
Tested on latest builds (Core 171, WMR 27) Issue persists.. Thoughts @StephenHodgson ?

**Comment by StephenHodgson** [comment]
No idea.

**Comment by StephenHodgson** [comment]
Are you able to get spatial awareness working in the editor with remote hololens?

**Comment by SimonDarksideJ** [comment]
I'll try and do a build to my device.  But these are being spammed even if just running in WMR
