### ISSUE TITLE
UWP APPX Build fails for VS 2019 when VS 2017 is not installed

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/WindowsMixedReality#60]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

When a dev only has 2019 installed the build window fails

## To Reproduce

1. Ensure only VS 2019 is installed
2. Build APPX for UWP
3. See error

## Expected behavior

Devs should be able to build the appx with either 2017 or 2019 depending on what's availible.

## Actual behavior

Can only build appx for VS 2017

## Your Setup (please complete the following information)

- Unity Version 2019.1.7f1
- XRTK Version bea8cd15c072d8b398fafb533f3c7d1df243114e

## Target Platform (please complete the following information)

- UWP

## Additional context

Might be related to how Unity creates the initial solution and project files. After being prompted to update the solution to a later version the appx build will succeed.  We might want to do something similar if only VS 2019 is found or a specific uwp sdk version is selected.

**Comment by FejZa** [comment]
I am pretty sure this is going to go away with moving past 2019.1. 2019.1 still generates a VS solution that needs to be retargeted to build tools v142 to properly build.

**Comment by StephenHodgson** [comment]
We also need to move the build tools into their platform projects respectively as well.
