### ISSUE TITLE
Update package to use fully native APIs

### ISSUE THREAD

**Issue by StephenHodgson** [XRTK/WindowsMixedReality#83]
# XRTK - Mixed Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

As part of our move to break dependencies on the XR SDK manager and plugin architecture, we should make strides to try and update this package to use the native windows APIs.

**Comment by FejZa** [comment]
My first question would be, where's the docs for that? Where can we find any sort of documentation and guidlines on native APIs. If we don't have that, it's just going to be a huge game of trial and error until Unity or Microsoft decides to lock us out and does breaking changes and we have to start over.

**Comment by StephenHodgson** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial?view=winrt-19041

**Comment by StephenHodgson** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.spatial?view=winrt-19041

**Comment by StephenHodgson** [comment]
> until Unity or Microsoft decides to lock us out and does breaking changes and we have to start over

Both if these companies have made promises to stay open and provide an open ecosystem. But all software depending on something else has this same problem. Let's worry about that when we get there. These APIs have been around for almost 5 years, I'm sure it'll be fine.

Plus we designed the xrtk to be adaptable, and more resilient to breaking changes to the consumer in the long term.

**Comment by FejZa** [comment]
All right.
