### ISSUE TITLE
Discussion: Unity 2020.1 and XR Plugin Management

### ISSUE THREAD

**Issue by FejZa** [XRTK/WindowsMixedReality#94]
# XRTK - Mixed Reality Toolkit

## What's the discussion about? Please describe

With Unity 2020.1 the legacy XR system is now fully dropped and unavailable.
Let's discuss and gather information what that implies for the XRTK WMR module here.

## Summary so far

- XRTK WMR package has a dependency on the legacy WMR UPM package, which is not available for 2020.1 onwards anymore

**Comment by StephenHodgson** [comment]
You should be able to directly use the windows namespace and APIs in the uwp build target

**Comment by FejZa** [comment]
Yes, that works. It's more about the WMR plugin itself. The legacy XR system and packages are gone now. The only option at this time is the new XR Plugin management.

**Comment by StephenHodgson** [comment]
The other option is to go full native. Probably the best option tbh.

**Comment by FejZa** [comment]
True, that's the long term option / more work option and probably the safest bet.

**Comment by SimonDarksideJ** [comment]
Well, we had always planned for the WMR system to use the Native API's rather than the Unity XR namespace.  We can relay on the handler being configured, we just wouldn't use it.

**Comment by FejZa** [comment]
I know. I am just looking for actually applicable solutions here. There is too much "planning" happening. But those things require tons of work and people who can do it. And if I'm honest I can't talked that.

I am looking at the XR management system now to understand whether it's really as bad as it's being made and whether it's something that can at least be used until the native bindings are available.

**Comment by FejZa** [comment]
Ok, so so far it seems to get XRTK-WMR to work with 2020.1 on a short-term removing the package's dependency to `com.unity.xr.windowsmr.metro` as that package can't be resolved anymore.

**Comment by StephenHodgson** [comment]
See https://github.com/XRTK/WindowsMixedReality/issues/83

**Comment by FejZa** [comment]
Closing this while working on some experiments regarding 2020.X
