### ISSUE TITLE
GameObject destroy errors reported in editor on the UWP platform

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/WindowsMixedReality#97]
# XRTK - Mixed Reality Toolkit Bug Report

## Describe the bug

There seems to be an issue with the Spatial Object management where it is cleared prematurely in the editor when the scene is closed.

## To Reproduce

1. Switch to UWP platform
2. Run XRTK in the editor
3. Stop the editor

## Expected behavior

No errors

## Your Setup

- Operation system : Windows
- Unity Version : 2019.1.4
- XRTK Version 0.2.0

**Comment by StephenHodgson** [comment]
When I stared the Holographic emulation everything seemed to work fine for me.
I also didn't have a problem when the WMR Portal was running as well. This seems to only happen when we're not targeting a 3d platform. Maybe we should try to disable the spatial understanding when a compatible device isn't found.

@FejZa could you possibly troubleshoot this with your device connected to the editor?

**Comment by FejZa** [comment]
Will do

**Comment by StephenHodgson** [comment]
One other interesting thing to note, when starting, then stopping emulation and trying this again in the editor, I didn't get the errors again until after I restarted the editor.

**Comment by StephenHodgson** [comment]
Here's the list of errors I'm getting atm:

```
Can't destroy Transform component of 'Main Camera'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'UIRaycastCamera'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Meshes'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
	
Can't destroy Transform component of 'Blank Spatial Mesh GameObject'. If you want to destroy the game object, please call 'Destroy' on the game object instead. Destroying the transform component is not allowed.
```

So the things I don't understand. We're not trying to destroy any transforms in our implementation. We call Destroy on the GameObjects themselves.

I'm wondering if these errors are coming from somewhere in Unity's internal implementation as the scene is cleaned up.

**Comment by StephenHodgson** [comment]
Edited the errors with the internal callstacks
